---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Update
      apt:
        name: '*'
        state: latest
        update_cache: yes
    
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Enable nginx
      systemd:
        name: nginx
        state: started

    - name: Install vim
      apt:
        name: vim
        state: latest
