---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Update
      apt:
        name: '*'
        state: latest
        update_cache: yes
    
    - name: Install vim
      apt:
        name: vim
        state: latest
